// Country display mapping.
//
// The backend stores/accepts the original country code or name (e.g. "DE",
// "United States"). The UI shows the full COUNTRY NAME (India, United States)
// — not a nationality demonym — while the stored value is left untouched.
//
// Lookup keys are normalised to UPPERCASE and cover ISO-2 codes, a few ISO-3
// codes, and full country names. Anything not found falls back to the original
// value, so entries that are already country names pass straight through and
// unknown codes display verbatim rather than breaking the UI.

const COUNTRY_BY_CODE: Record<string, string> = {
  // ── ISO-2 codes (as stored in country_risk.csv) ──
  AG: 'Antigua and Barbuda',
  AL: 'Albania',
  AM: 'Armenia',
  AO: 'Angola',
  AR: 'Argentina',
  AT: 'Austria',
  AW: 'Aruba',
  AZ: 'Azerbaijan',
  BA: 'Bosnia and Herzegovina',
  BB: 'Barbados',
  BD: 'Bangladesh',
  BE: 'Belgium',
  BF: 'Burkina Faso',
  BG: 'Bulgaria',
  BH: 'Bahrain',
  BI: 'Burundi',
  BJ: 'Benin',
  BM: 'Bermuda',
  BO: 'Bolivia',
  BS: 'Bahamas',
  BZ: 'Belize',
  CD: 'DR Congo',
  CF: 'Central African Republic',
  CG: 'Republic of the Congo',
  CI: "Côte d'Ivoire",
  CK: 'Cook Islands',
  CL: 'Chile',
  CM: 'Cameroon',
  CO: 'Colombia',
  CR: 'Costa Rica',
  CS: 'Serbia and Montenegro',
  CV: 'Cape Verde',
  CW: 'Curaçao',
  CY: 'Cyprus',
  CZ: 'Czechia',
  DJ: 'Djibouti',
  DK: 'Denmark',
  DM: 'Dominica',
  DO: 'Dominican Republic',
  DZ: 'Algeria',
  EC: 'Ecuador',
  EE: 'Estonia',
  EG: 'Egypt',
  ER: 'Eritrea',
  ES: 'Spain',
  ET: 'Ethiopia',
  EU: 'European Union',
  FI: 'Finland',
  FJ: 'Fiji',
  FO: 'Faroe Islands',
  GA: 'Gabon',
  GD: 'Grenada',
  GE: 'Georgia',
  GG: 'Guernsey',
  GH: 'Ghana',
  GI: 'Gibraltar',
  GM: 'Gambia',
  GN: 'Guinea',
  GQ: 'Equatorial Guinea',
  GR: 'Greece',
  GT: 'Guatemala',
  GW: 'Guinea-Bissau',
  GY: 'Guyana',
  HK: 'Hong Kong',
  HN: 'Honduras',
  HR: 'Croatia',
  HT: 'Haiti',
  HU: 'Hungary',
  ID: 'Indonesia',
  IE: 'Ireland',
  IL: 'Israel',
  IM: 'Isle of Man',
  IO: 'British Indian Ocean Territory',
  IS: 'Iceland',
  IT: 'Italy',
  JE: 'Jersey',
  JM: 'Jamaica',
  JO: 'Jordan',
  KE: 'Kenya',
  KG: 'Kyrgyzstan',
  KH: 'Cambodia',
  KI: 'Kiribati',
  KM: 'Comoros',
  KN: 'Saint Kitts and Nevis',
  KW: 'Kuwait',
  KY: 'Cayman Islands',
  KZ: 'Kazakhstan',
  LA: 'Laos',
  LB: 'Lebanon',
  LC: 'Saint Lucia',
  LI: 'Liechtenstein',
  LK: 'Sri Lanka',
  LR: 'Liberia',
  LT: 'Lithuania',
  LU: 'Luxembourg',
  LV: 'Latvia',
  MA: 'Morocco',
  MC: 'Monaco',
  MD: 'Moldova',
  ME: 'Montenegro',
  MG: 'Madagascar',
  MH: 'Marshall Islands',
  MK: 'North Macedonia',
  ML: 'Mali',
  MN: 'Mongolia',
  MO: 'Macau',
  MR: 'Mauritania',
  MT: 'Malta',
  MU: 'Mauritius',
  MV: 'Maldives',
  MW: 'Malawi',
  MY: 'Malaysia',
  MZ: 'Mozambique',
  NA: 'Namibia',
  NE: 'Niger',
  NI: 'Nicaragua',
  NO: 'Norway',
  NZ: 'New Zealand',
  OM: 'Oman',
  PA: 'Panama',
  PE: 'Peru',
  PH: 'Philippines',
  PL: 'Poland',
  PS: 'Palestine',
  PT: 'Portugal',
  PW: 'Palau',
  PY: 'Paraguay',
  QA: 'Qatar',
  RO: 'Romania',
  RS: 'Serbia',
  RW: 'Rwanda',
  SC: 'Seychelles',
  SE: 'Sweden',
  SI: 'Slovenia',
  SK: 'Slovakia',
  SL: 'Sierra Leone',
  SM: 'San Marino',
  SN: 'Senegal',
  SO: 'Somalia',
  SR: 'Suriname',
  ST: 'São Tomé and Príncipe',
  SV: 'El Salvador',
  SX: 'Sint Maarten',
  SZ: 'Eswatini',
  TD: 'Chad',
  TG: 'Togo',
  TH: 'Thailand',
  TJ: 'Tajikistan',
  TM: 'Turkmenistan',
  TN: 'Tunisia',
  TO: 'Tonga',
  TT: 'Trinidad and Tobago',
  TV: 'Tuvalu',
  TW: 'Taiwan',
  TZ: 'Tanzania',
  UG: 'Uganda',
  UY: 'Uruguay',
  UZ: 'Uzbekistan',
  VC: 'Saint Vincent and the Grenadines',
  VG: 'British Virgin Islands',
  VN: 'Vietnam',
  VU: 'Vanuatu',
  WS: 'Samoa',
  XK: 'Kosovo',
  ZM: 'Zambia',

  // ── Common ISO-3 codes (in case the backend ever emits these) ──
  ARE: 'United Arab Emirates',
  AUS: 'Australia',
  CAN: 'Canada',
  CHN: 'China',
  DEU: 'Germany',
  FRA: 'France',
  GBR: 'United Kingdom',
  IND: 'India',
  IRN: 'Iran',
  JPN: 'Japan',
  NLD: 'Netherlands',
  PAK: 'Pakistan',
  PRK: 'North Korea',
  RUS: 'Russia',
  SAU: 'Saudi Arabia',
  SGP: 'Singapore',
  USA: 'United States',
  ZAF: 'South Africa',
}

/**
 * Returns the full country name for a country code or name. Values that are
 * already country names (e.g. "India", "United States") pass through, and
 * unknown values fall back to the original input so the UI never breaks.
 */
export function countryLabel(value?: string | null): string {
  if (!value) return ''
  const key = value.trim().toUpperCase()
  return COUNTRY_BY_CODE[key] || value
}

/**
 * Builds `{ value, label }` options for a country dropdown from raw backend
 * country codes/names, preserving the original value for submission and sorting
 * by the country name.
 */
export function toCountryOptions(codes: string[]): { value: string; label: string }[] {
  return codes
    .map((value) => ({ value, label: countryLabel(value) }))
    .sort((a, b) => a.label.localeCompare(b.label))
}
