// Nationality display mapping.
//
// The backend stores/accepts the original country code or name (e.g. "IN",
// "United States"). These are not user-friendly, so the UI shows the
// corresponding nationality (demonym) label instead — e.g. "Indian",
// "American" — while the underlying value sent to / stored by the API is
// always left untouched.
//
// Lookup keys are normalised to UPPERCASE and cover ISO-2 codes, ISO-3 codes,
// and full country names. Anything not found falls back to the original value
// so unknown codes are displayed verbatim rather than breaking the UI.

const NATIONALITY_MAP: Record<string, string> = {
  // ── Full country names (as stored in country_risk.csv) ──
  AFGHANISTAN: 'Afghan',
  AUSTRALIA: 'Australian',
  BELARUS: 'Belarusian',
  BRAZIL: 'Brazilian',
  CANADA: 'Canadian',
  CHINA: 'Chinese',
  CUBA: 'Cuban',
  FRANCE: 'French',
  GERMANY: 'German',
  INDIA: 'Indian',
  IRAN: 'Iranian',
  IRAQ: 'Iraqi',
  JAPAN: 'Japanese',
  LIBYA: 'Libyan',
  MEXICO: 'Mexican',
  MYANMAR: 'Burmese',
  NETHERLANDS: 'Dutch',
  NIGERIA: 'Nigerian',
  'NORTH KOREA': 'North Korean',
  PAKISTAN: 'Pakistani',
  RUSSIA: 'Russian',
  'SAUDI ARABIA': 'Saudi',
  SINGAPORE: 'Singaporean',
  'SOUTH AFRICA': 'South African',
  'SOUTH KOREA': 'South Korean',
  'SOUTH SUDAN': 'South Sudanese',
  SUDAN: 'Sudanese',
  SWITZERLAND: 'Swiss',
  SYRIA: 'Syrian',
  TURKEY: 'Turkish',
  UKRAINE: 'Ukrainian',
  'UNITED ARAB EMIRATES': 'Emirati',
  'UNITED KINGDOM': 'British',
  'UNITED STATES': 'American',
  VENEZUELA: 'Venezuelan',
  YEMEN: 'Yemeni',
  ZIMBABWE: 'Zimbabwean',

  // ── ISO-2 codes (as stored in country_risk.csv) ──
  AG: 'Antiguan',
  AL: 'Albanian',
  AM: 'Armenian',
  AO: 'Angolan',
  AR: 'Argentine',
  AT: 'Austrian',
  AW: 'Aruban',
  AZ: 'Azerbaijani',
  BA: 'Bosnian',
  BB: 'Barbadian',
  BD: 'Bangladeshi',
  BE: 'Belgian',
  BF: 'Burkinabé',
  BG: 'Bulgarian',
  BH: 'Bahraini',
  BI: 'Burundian',
  BJ: 'Beninese',
  BM: 'Bermudian',
  BO: 'Bolivian',
  BS: 'Bahamian',
  BZ: 'Belizean',
  CD: 'Congolese',
  CF: 'Central African',
  CG: 'Congolese',
  CI: 'Ivorian',
  CK: 'Cook Islander',
  CL: 'Chilean',
  CM: 'Cameroonian',
  CO: 'Colombian',
  CR: 'Costa Rican',
  CV: 'Cape Verdean',
  CW: 'Curaçaoan',
  CY: 'Cypriot',
  CZ: 'Czech',
  DJ: 'Djiboutian',
  DK: 'Danish',
  DM: 'Dominican',
  DO: 'Dominican',
  DZ: 'Algerian',
  EC: 'Ecuadorian',
  EE: 'Estonian',
  EG: 'Egyptian',
  ER: 'Eritrean',
  ES: 'Spanish',
  ET: 'Ethiopian',
  FI: 'Finnish',
  FJ: 'Fijian',
  FO: 'Faroese',
  GA: 'Gabonese',
  GD: 'Grenadian',
  GE: 'Georgian',
  GG: 'Guernsey',
  GH: 'Ghanaian',
  GI: 'Gibraltarian',
  GM: 'Gambian',
  GN: 'Guinean',
  GQ: 'Equatorial Guinean',
  GR: 'Greek',
  GT: 'Guatemalan',
  GW: 'Bissau-Guinean',
  GY: 'Guyanese',
  HK: 'Hong Konger',
  HN: 'Honduran',
  HR: 'Croatian',
  HT: 'Haitian',
  HU: 'Hungarian',
  ID: 'Indonesian',
  IE: 'Irish',
  IL: 'Israeli',
  IM: 'Manx',
  IS: 'Icelandic',
  IT: 'Italian',
  JE: 'Jerseyman',
  JM: 'Jamaican',
  JO: 'Jordanian',
  KE: 'Kenyan',
  KG: 'Kyrgyz',
  KH: 'Cambodian',
  KI: 'I-Kiribati',
  KM: 'Comoran',
  KN: 'Kittitian',
  KW: 'Kuwaiti',
  KY: 'Caymanian',
  KZ: 'Kazakhstani',
  LA: 'Lao',
  LB: 'Lebanese',
  LC: 'Saint Lucian',
  LI: 'Liechtensteiner',
  LK: 'Sri Lankan',
  LR: 'Liberian',
  LT: 'Lithuanian',
  LU: 'Luxembourgish',
  LV: 'Latvian',
  MA: 'Moroccan',
  MC: 'Monégasque',
  MD: 'Moldovan',
  ME: 'Montenegrin',
  MG: 'Malagasy',
  MH: 'Marshallese',
  MK: 'Macedonian',
  ML: 'Malian',
  MN: 'Mongolian',
  MO: 'Macanese',
  MR: 'Mauritanian',
  MT: 'Maltese',
  MU: 'Mauritian',
  MV: 'Maldivian',
  MW: 'Malawian',
  MY: 'Malaysian',
  MZ: 'Mozambican',
  NA: 'Namibian',
  NE: 'Nigerien',
  NI: 'Nicaraguan',
  NO: 'Norwegian',
  NZ: 'New Zealander',
  OM: 'Omani',
  PA: 'Panamanian',
  PE: 'Peruvian',
  PH: 'Filipino',
  PL: 'Polish',
  PS: 'Palestinian',
  PT: 'Portuguese',
  PW: 'Palauan',
  PY: 'Paraguayan',
  QA: 'Qatari',
  RO: 'Romanian',
  RS: 'Serbian',
  RW: 'Rwandan',
  SC: 'Seychellois',
  SE: 'Swedish',
  SI: 'Slovenian',
  SK: 'Slovak',
  SL: 'Sierra Leonean',
  SM: 'Sammarinese',
  SN: 'Senegalese',
  SO: 'Somali',
  SR: 'Surinamese',
  ST: 'São Toméan',
  SV: 'Salvadoran',
  SZ: 'Swazi',
  TD: 'Chadian',
  TG: 'Togolese',
  TH: 'Thai',
  TJ: 'Tajik',
  TM: 'Turkmen',
  TN: 'Tunisian',
  TO: 'Tongan',
  TT: 'Trinidadian',
  TV: 'Tuvaluan',
  TW: 'Taiwanese',
  TZ: 'Tanzanian',
  UG: 'Ugandan',
  UY: 'Uruguayan',
  UZ: 'Uzbekistani',
  VC: 'Vincentian',
  VN: 'Vietnamese',
  VU: 'Ni-Vanuatu',
  WS: 'Samoan',
  XK: 'Kosovar',
  ZM: 'Zambian',

  // ── Common ISO-3 codes (in case the backend ever emits these) ──
  ARE: 'Emirati',
  AUS: 'Australian',
  CAN: 'Canadian',
  CHN: 'Chinese',
  DEU: 'German',
  FRA: 'French',
  GBR: 'British',
  IND: 'Indian',
  IRN: 'Iranian',
  JPN: 'Japanese',
  NLD: 'Dutch',
  PAK: 'Pakistani',
  PRK: 'North Korean',
  RUS: 'Russian',
  SAU: 'Saudi',
  SGP: 'Singaporean',
  USA: 'American',
  ZAF: 'South African',
}

/**
 * Returns the human-readable nationality (demonym) label for a country code or
 * name. Unknown values fall back to the original input unchanged so the UI
 * never breaks on an unmapped code.
 */
export function nationalityLabel(value?: string | null): string {
  if (!value) return ''
  const key = value.trim().toUpperCase()
  return NATIONALITY_MAP[key] || value
}

/**
 * Builds `{ value, label }` options for a nationality dropdown from raw backend
 * country codes/names, preserving the original value for submission and sorting
 * by the display label.
 */
export function toNationalityOptions(codes: string[]): { value: string; label: string }[] {
  return codes
    .map((value) => ({ value, label: nationalityLabel(value) }))
    .sort((a, b) => a.label.localeCompare(b.label))
}
